# Font configuration (changes require restart)
font:
  # The size to use.
  size: 11
  # The normal (roman) font face to use.
  normal:
    # family: UbuntuMono Nerd Font
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    # family: UbuntuMono Nerd Font
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: FiraCode Nerd Font
    # family: UbuntuMono Nerd Font
    # Style can be specified to pick a specific face.
    style: Italic

# Shubham's modified Pop-XTerm's default colors
colors:
   # Default colors
   primary:
     background: '#333333'
     foreground: '#e5e5e5'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
   cursor:
     text: '#49B9C7'
     cursor: '#F6F6F6'
     
   # Normal colors
   normal:
     black:   '#000000'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#dcc356'
     blue:    '#136ee3'
     magenta: '#cd00cd'
     cyan:    '#00cdcd'
     white:   '#e5e5e5'

   # Bright colors
   bright:
     black:   '#7f7f7f'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#ffff00'
     blue:    '#5c5cff'
     magenta: '#ff00ff'
     cyan:    '#00ffff'
     white:   '#ffffff'
   # Selection colors
   #
   # Colors which should be used to draw the selection area.
   #
   # Allowed values are CellForeground and CellBackground, which reference the
   # affected cell, or hexadecimal colors like #ff00ff.
   selection:
     text: '#FFFFFF'
     background: '#48B9C7'

background_opacity: 0.95
