# env:
  # TERM: xterm-256color

window:
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: 'none'
  # Font configuration (changes require restart)
font:
  # The size to use.
  size: 11
  # The normal (roman) font face to use.
  normal:
    # family: JetBrains Mono # (A very good option)
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    # family: JetBrains Mono
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    # family: JetBrains Mono
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    # style: Italic # Fira Code doesn't have italic styling

# Shubham's modified Pop-XTerm's default colors
colors:
   # Default colors
   primary:
     background: '#333333'
     foreground: '#e5e5e5'

  # Cursor colors
   cursor:
     text: '#49B9C7'
     cursor: '#F6F6F6'
     
   # Normal colors
   normal:
     black:   '#000000'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#dcc356'
     blue:    '#136ee3'
     magenta: '#cd00cd'
     cyan:    '#00cdcd'
     white:   '#e5e5e5'

   # Bright colors
   bright:
     black:   '#7f7f7f'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#ffff00'
     blue:    '#5c5cff'
     magenta: '#ff00ff'
     cyan:    '#00ffff'
     white:   '#ffffff'
   # Selection colors
   selection:
     text: '#FFFFFF'
     background: '#48B9C7'

background_opacity: 0.99

# TODO: Still not sure if Alacritty is using the primary clipboard, debug this while customizing mouse options.
save_to_clipboard: true

# TODO: Customize mouse options.
