# Configuration for Alacritty, the GPU enhanced terminal emulator
# All Alacritty configuration is present @ https://github.com/alacritty/alacritty/blob/master/alacritty.yml

# TODO: Make separate config files for themes
# Import additional configuration files
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
import:
  # - /path/to/alacritty.yml
  # - '~/.config/alacritty/alacritty.yml' # TODO: giving error right now
  - '~/.config/alacritty/colorschemes.yml'
  # -  '~/.config/alacritty/visual.yml'
  # -  '~/.config/alacritty/binding.yml'
  # -  '~/.config/alacritty/operation.yml'

# TODO: Remove this after figuring out how to export `ls` colors in zsh, `tree` is also not displaying colors.
# env:
#   TERM: xterm-256color

cursor:
  # Cursor style

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On

window:
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: 'none'

# Font configuration (changes require restart)
font:
  # The size to use.
  size: 11
  # The normal (roman) font face to use.
  normal:
    ## family: JetBrains Mono # (A very good option)
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    ## family: JetBrains Mono
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    ## family: JetBrains Mono
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Italic # Fira Code doesn't have italic styling

window.opacity: 0.99

# TODO: Still not sure if Alacritty is using the primary clipboard, debug this while customizing mouse options.
save_to_clipboard: true

# TODO: Customize mouse options.
